# Generated by Django 3.1.4 on 2021-03-31 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=500)),
                ('gtm_id', models.CharField(max_length=500)),
                ('ga_measurement_id', models.CharField(max_length=500)),
                ('segment_key', models.CharField(max_length=500)),
                ('target_div', models.CharField(max_length=500)),
                ('product_name_selector', models.CharField(max_length=500)),
                ('insert_before', models.CharField(max_length=500)),
                ('product_page_identifier', models.CharField(max_length=500)),
                ('product_page_regex', models.CharField(max_length=500)),
            ],
        ),
    ]
