# Generated by Django 3.1.4 on 2021-04-05 16:53

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210405_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='consumer_key',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=500, null=True)),
        ),
        migrations.AlterField(
            model_name='store',
            name='consumer_secret',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=500, null=True)),
        ),
    ]
