# Generated by Django 3.1.4 on 2021-04-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210405_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_logo_url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='ga_measurement_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='gtm_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='insert_before',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_name_selector',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_page_identifier',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='segment_key',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='target_div',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
