# Generated by Django 3.1.4 on 2021-04-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210406_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='product_page_regex',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
