# Generated by Django 3.1.4 on 2021-04-21 20:25

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_store_fare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='store',
            name='consumer_key',
        ),
        migrations.RemoveField(
            model_name='store',
            name='consumer_secret',
        ),
        migrations.RemoveField(
            model_name='store',
            name='ga_measurement_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='gtm_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='insert_before',
        ),
        migrations.RemoveField(
            model_name='store',
            name='product_name_selector',
        ),
        migrations.RemoveField(
            model_name='store',
            name='product_page_identifier',
        ),
        migrations.RemoveField(
            model_name='store',
            name='product_page_regex',
        ),
        migrations.RemoveField(
            model_name='store',
            name='segment_key',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_logo_url',
        ),
        migrations.RemoveField(
            model_name='store',
            name='target_div',
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtm_id', models.CharField(max_length=500, null=True)),
                ('ga_measurement_id', models.CharField(max_length=500, null=True)),
                ('segment_key', models.CharField(max_length=500, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=1000, null=True)),
                ('consumer_key', django_cryptography.fields.encrypt(models.CharField(max_length=500, null=True))),
                ('consumer_secret', django_cryptography.fields.encrypt(models.CharField(max_length=500, null=True))),
                ('api_url', models.CharField(max_length=1000, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='Front',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_logo_url', models.CharField(max_length=2000, null=True)),
                ('target_div', models.CharField(max_length=500, null=True)),
                ('product_name_selector', models.CharField(max_length=500, null=True)),
                ('insert_before', models.CharField(max_length=500, null=True)),
                ('product_page_identifier', models.CharField(max_length=500, null=True)),
                ('product_page_regex', models.CharField(max_length=500, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, null=True)),
                ('last_name', models.CharField(max_length=2000, null=True)),
                ('email', models.CharField(max_length=2000, null=True)),
                ('accepts_marketing', models.BooleanField(default=False)),
                ('accepts_marketing_updated_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
    ]
