# Generated by Django 3.1.4 on 2021-04-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_customers_customers_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customers_code',
            field=models.BigIntegerField(),
        ),
    ]
