# Generated by Django 3.1.4 on 2021-04-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210422_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='front',
            name='button_insert_before',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='front',
            name='button_target_div',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
