# Generated by Django 3.1.4 on 2020-12-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymvp', '0002_snippet_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='document',
            field=models.FileField(default='file', upload_to=''),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
