# Generated by Django 3.1.4 on 2020-12-31 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymvp', '0004_auto_20201231_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='uploaded_at',
        ),
    ]
