# Generated by Django 3.1.4 on 2021-01-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymvp', '0007_snippet_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='document',
            field=models.FileField(upload_to=None),
        ),
    ]
