# Generated by Django 3.1.4 on 2021-01-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymvp', '0013_auto_20210111_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=987654321, max_length=9),
            preserve_default=False,
        ),
    ]
