version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/code
    expose:
      - 8000
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/code/cactusco/service_account_key.json
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
  certs: