# Generated by Django 3.1.4 on 2021-01-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_suscription_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscription',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
