# Generated by Django 3.1.4 on 2021-04-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='company_url',
            field=models.CharField(default='htttp', max_length=2000),
            preserve_default=False,
        ),
    ]
