# Generated by Django 3.1.4 on 2021-04-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20210416_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company_url',
        ),
        migrations.AddField(
            model_name='contact',
            name='website',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
