# Generated by Django 3.1.4 on 2021-03-20 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(unique=True)),
                ('sku', models.CharField(default=None, max_length=2000)),
                ('name', models.CharField(max_length=2000)),
                ('href', models.CharField(default=None, max_length=2000)),
                ('company', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPredictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('company', models.CharField(max_length=500)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productattributes', to_field='product_id')),
                ('recommended_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_id', to='api.productattributes', to_field='product_id')),
            ],
        ),
    ]
