# Generated by Django 3.1.4 on 2021-03-31 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upsellpredictions',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='upsellpredictions',
            name='recommended_code',
        ),
        migrations.DeleteModel(
            name='CrossSellPredictions',
        ),
        migrations.DeleteModel(
            name='ProductAttributes',
        ),
        migrations.DeleteModel(
            name='UpSellPredictions',
        ),
    ]
