<template>
  <!-- component -->
    <div id="pricing" class="py-12 flex justify-center items-center">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="text-center font-semibold">
                <h1 class="text-5xl">
                    <span>Planes </span>
                    <span class="text-blue-600 tracking-wide">a tu Medida </span>
                </h1>
                <p class="pt-6 text-xl text-gray-400 font-normal w-full px-8 md:w-full">
                    Si no estas contento contáctanos dentro de los primeros 14 días y te devolveremos lo pagado, sin preguntas.
                </p>
            </div>
            <div class="pt-6 flex flex-row flex-wrap">
                <!-- Basic Card -->
                <div class="w-80 p-8 m-4 bg-white text-center rounded-xl shadow-xl">
                    <h1 class="text-black font-semibold text-2xl">Emprendedor</h1>
                    <p class="pt-2 tracking-wide">
                        <span class="text-gray-400 align-top">$ </span>
                        <span class="text-3xl font-semibold">9.990</span>
                        <span class="text-gray-400 font-medium">/ mes</span>
                    </p>
                    <hr class="mt-4 border-1">
                    <div class="pt-8">
                        <p class="font-semibold text-gray-400 text-left">
                            <span class="material-icons align-middle">
                                done
                            </span>
                            <span class="pl-2">
                                Hasta <span class="text-black">200 SKU's</span>
                            </span>
                        </p>
                        <p class="font-semibold text-gray-400 text-left pt-5">
                            <span class="material-icons align-middle">
                                done
                            </span>
                            <span class="pl-2">
                                <span class="text-black">5.000 sesiones</span> / mes
                            </span>
                        </p>
                        <p class="font-semibold text-gray-400 text-left pt-5">
                            <span class="material-icons align-middle">
                                done
                            </span>
                            <span class="pl-2">
                                <span class="text-black"> Up-Sellings</span>
                            </span>
                        </p>

                        <a href="#" class="">
                            <p class="w-full py-4 bg-blue-600 mt-8 rounded-xl text-white">
                                <span class="font-medium">
                                    Quiero este Plan
                                </span>
                                <span class="pl-2 material-icons align-middle text-sm">
                                    east
                                </span>
                            </p>
                        </a>
                    </div>
                </div>
                <!-- StartUp Card -->
                <div class="w-80 p-8 m-4 bg-gray-900 text-center rounded-xl text-white shadow-2xl">
                    <h1 class="text-white font-semibold text-2xl">Startup</h1>
                    <p class="pt-2 tracking-wide">
                        <span class="text-gray-400 align-top">$ </span>
                        <span class="text-3xl font-semibold">29.990</span>
                        <span class="text-gray-400 font-medium">/ mes</span>
                    </p>
                    <hr class="mt-4 border-1 border-gray-600">
                    <div class="pt-8">
                        <p class="font-semibold text-gray-400 text-left">
                            <span class="material-icons align-middle">
                                done
                            </span>
                            <span class="pl-2">
                                Hasta <span class="text-white">5.000 SKU's</span>
                            </span>
                        </p>
                        <p class="font-semibold text-gray-400 text-left pt-5">
                            <span class="material-icons align-middle">
                                done
                            </span>
                            <span class="pl-2">
                                <span class="text-white">100.000 sesiones</span> / mes
                            </span>
                        </p>
                        <p class="font-semibold text-gray-400 text-left pt-5">
                            <span class="material-icons align-middle">
                                done
                            </span>
                            <span class="pl-2">
                                <span class="text-white">Up, Cross y Vistos recientemente</span>
                            </span>
                        </p>

                        <a href="#" class="">
                            <p class="w-full py-4 bg-blue-600 mt-8 rounded-xl text-white">
                                <span class="font-medium">
                                    Quiero este Plan
                                </span>
                                <span class="pl-2 material-icons align-middle text-sm">
                                    east
                                </span>
                            </p>
                        </a>
                    </div>
                    <!-- <div class="absolute top-4 right-4">
                        <p class="bg-blue-700 font-semibold px-4 py-1 rounded-full uppercase text-xs">Popular</p>
                    </div> -->
                </div>
                <!-- Enterprise Card -->
                <div class="w-80 p-8 m-4 bg-white text-center rounded-xl shadow-xl">
                    <h1 class="text-black font-semibold text-2xl">Gran Empresa</h1>
                    <p class="pt-2 tracking-wide">
                        <span class="text-2xl font-semibold">Contáctanos </span>
                    </p>
                    <hr class="mt-4 border-1">
                    <div class="pt-8">
                        <p class="font-semibold text-gray-400 text-left">
                            <span class="material-icons align-middle">
                                done
                            </span>
                            <span class="pl-2">
                                + <span class="text-black">5.000 SKU's</span>
                            </span>
                        </p>
                        <p class="font-semibold text-gray-400 text-left pt-5">
                            <span class="material-icons align-middle">
                                done
                            </span>
                            <span class="pl-2">
                                + <span class="text-black">100.000 sesiones / mes</span>
                            </span>
                        </p>
                        <p class="font-semibold text-gray-400 text-left pt-5">
                            <span class="material-icons align-middle">
                                done
                            </span>
                            <span class="pl-2">
                                <span class="text-black">Up, Cross y Vistos recientemente</span> 
                            </span>
                        </p>

                        <a href="#" class="">
                            <p class="w-full py-4 bg-blue-600 mt-8 rounded-xl text-white">
                                <span class="font-medium">
                                    Quiero este Plan
                                </span>
                                <span class="pl-2 material-icons align-middle text-sm">
                                    east
                                </span>
                            </p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <link rel="stylesheet" href="/path/to/material-icons/iconfont/material-icons.css">
    </div>
</template>

<script>
export default {
    name: 'Pricing'
}
</script>

<style>

</style>