# Generated by Django 3.1.4 on 2020-12-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_snippet_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='document',
            field=models.FileField(upload_to='documents'),
        ),
    ]
