# Generated by Django 3.1.4 on 2020-12-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='last_name',
            field=models.CharField(default='Last_name', max_length=100),
        ),
    ]
