# Generated by Django 3.1.4 on 2020-12-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_auto_20201231_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='uploaded_at',
            field=models.DateTimeField(default='2020-12-31'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='document',
            field=models.FileField(upload_to='documents/%Y-%m-%d'),
        ),
    ]
