# Generated by Django 3.1.4 on 2020-12-31 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0006_auto_20201231_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
