# Generated by Django 3.1.4 on 2021-01-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0009_auto_20210108_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydata',
            old_name='user_id',
            new_name='user',
        ),
    ]
