# Generated by Django 3.1.4 on 2021-01-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0010_auto_20210108_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='recieve_info_flag',
            field=models.BooleanField(default=False),
        ),
    ]
