
# Generated by Django 3.1.4 on 2021-04-01 20:46


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_created_at', models.DateTimeField()),
                ('product_code', models.IntegerField()),
                ('sku', models.CharField(default=None, max_length=2000)),
                ('name', models.CharField(max_length=2000)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('img_url', models.CharField(default=None, max_length=2000)),
                ('permalink', models.CharField(max_length=2000)),
                ('status', models.CharField(max_length=500)),
                ('stock_quantity', models.BooleanField(blank=True, default=None, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpSellPredictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_created_at', models.DateTimeField()),
                ('distance', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productattributes')),
                ('recommended_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_sell', to='products.productattributes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_created_at', models.DateTimeField()),
                ('user', models.CharField(max_length=2000)),
                ('prod_qty', models.IntegerField()),
                ('bill', models.CharField(max_length=2000)),
                ('prod_name', models.CharField(max_length=2000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productattributes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrossSellPredictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_created_at', models.DateTimeField()),
                ('distance', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productattributes')),
                ('recommended_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_sell', to='products.productattributes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
