# Generated by Django 3.1.4 on 2021-04-03 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattributes',
            old_name='record_created_at',
            new_name='product_created_at',
        ),
        migrations.RemoveField(
            model_name='crosssellpredictions',
            name='record_created_at',
        ),
        migrations.RemoveField(
            model_name='orderattributes',
            name='record_created_at',
        ),
        migrations.RemoveField(
            model_name='upsellpredictions',
            name='record_created_at',
        ),
    ]
