# Generated by Django 3.1.4 on 2021-04-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productattributes_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributes',
            name='product_code',
            field=models.BigIntegerField(),
        ),
    ]
