# Generated by Django 3.1.4 on 2021-04-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productattributes_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributes',
            name='sku',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
