# Generated by Django 3.1.4 on 2021-04-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210410_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributes',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
