# Generated by Django 3.1.4 on 2021-04-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210413_2117'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='crosssellpredictions',
            index=models.Index(fields=['-distance'], name='cross_distance_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributes',
            index=models.Index(fields=['name'], name='products_pr_name_db78e5_idx'),
        ),
        migrations.AddIndex(
            model_name='upsellpredictions',
            index=models.Index(fields=['-distance'], name='up_distance_idx'),
        ),
    ]
