# Generated by Django 3.1.4 on 2021-04-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210415_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattributes',
            old_name='discounted_price',
            new_name='compare_at_price',
        ),
    ]
