# Generated by Django 3.1.4 on 2021-04-21 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210421_2025'),
        ('products', '0008_auto_20210420_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPredictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customers')),
                ('recommended_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_prediction', to='products.productattributes')),
            ],
        ),
        migrations.AddIndex(
            model_name='customerpredictions',
            index=models.Index(fields=['-rate'], name='up_rate_idx'),
        ),
    ]
