# Generated by Django 3.1.4 on 2021-04-22 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_customers_customers_code'),
        ('products', '0009_auto_20210421_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderattributes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customers'),
        ),
    ]
