# Generated by Django 3.1.4 on 2021-04-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210423_1420'),
        ('products', '0010_productattributes_vendor'),
    ]

    operations = [
    ]
